### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by crshrprt** [brummer10/StompTuner#1]
Thank you for this interesting plugin.

I can't find if the source is released under a license. Is there a license?

**Comment by brummer10** [comment]
The licenses been given in each file on top. 
The plugin itself is released under 
SPDX-License-Identifier:  GPL-2.0 license  (or later) 
the included zita-resampler use the
SPDX-License-Identifier: GPL-3.0 license  (or later) 
the DPF framework is under the
SPDX-License-Identifier:  ISC
and the Cairo Widgets I released under the 
SPDX-License-Identifier:  0BSD 

so, that leads to the GPL-3.0 license (or later)  for the complete project, but not for the single included files.

**Comment by crshrprt** [comment]
I was used to see a LICENSE file in your projects. I was afraid something changed. Thank you for your kind answer.

**Comment by falkTX** [comment]
it is still useful to have a global/root license file, to indicate what license the final product is meant to have.
there should no need to scan all the files just to find what a project license is.

**Comment by brummer10** [comment]
Okay, for clarification I add a LICENSE file identify the Project is under the GPL-3.0-or-later, in the root folder now. 
I'll close this issue as solved therefore.
