### ISSUE TITLE
DPF does not use vestige

### ISSUE THREAD

**Issue by falkTX** [brummer10/StompTuner#2]
Just a small clarification, DPF was using vestige initially but with it being GPLv2+ it caused issues if we want to release commercial/proprietary plugins made with DPF.
So several months ago (years?) I changed it to use yet another vst2 reverse-engineered project https://github.com/Xaymar/vst2sdk
This one is more liberally licensed.

Details on this on https://github.com/DISTRHO/DPF/blob/main/LICENSING.md

**Comment by brummer10** [comment]
Thanks for clarify. Somehow I've known that, but forgot to fix it in the README. 
Done now.

regards
hermann

**Comment by falkTX** [comment]
cool thanks
