### ISSUE TITLE
I think the frequency is wrong. 

### ISSUE THREAD

**Issue by felixniemeyer** [brummer10/StompTuner#3]
It'd be so cool to have a tuner plugin for tuning my guitar in Bitwig!

Using the CLAP version of the plugin. 

When I create a pure sine C3 the StompTuner unfortunately determines a different frequency: 

![image](https://github.com/brummer10/StompTuner/assets/5720176/ad63e9b1-4fd1-47bf-8dec-27880526e17a)

I tried restarting the audio engine but that didn't help. 

Let me know, what I can try or test.

**Comment by felixniemeyer** [comment]
Found the cause by trying a different sample rate in jack: 

![image](https://github.com/brummer10/StompTuner/assets/5720176/91f562c8-461c-4bbd-8255-19d970cfe64a)

It works for 44100 but is wrong for 48000.

I think StompTuner should work for any samplerate, no?

**Comment by brummer10** [comment]
> I think StompTuner should work for any samplerate, no?

Sure. 
Could it be that Bitwig init the plugin with the wrong Sample Rate and changed that afterwards?
I'm using 48kHz all the time, but never using Bitwig. StompTuner works well with Reaper, Ardour, Carla, Qtractor, Renoise, . . . 
I must admit that Sample Rate changes during life time wasn't fetched by the plugin, I may implement that.

Would also be of some interest if the same issue exist with the VST2/3 version?

**Comment by felixniemeyer** [comment]
Hey, i did some tests: 

1. I started jack2 with 48kHz and then started Bitwig. The CLAP plugin would still return wrong frequencies. I think in this case, bitwig does not initiate the plugin with one sample rate first in order to then switch to the actual sample rate. 

2. I tried out the VST version and with that version the frequencies returned by StompTuner are correct! Even when jack is running with 48kHz 

Let me know, how I can assist further.

**Comment by brummer10** [comment]
That's good to know. So it's the Clap version only. I need to talk with @falkTX if, by any chance the wrong SampleRate may be introduced by the DPF Clap wrapper.

**Comment by brummer10** [comment]
I talked with @falkTX, and yes, it's the DPF Clap wrapper introducing the wrong Sample Rate. I need to handle the Sample Rate change callback in order to get it working correct in the Clap format as the correct Sample Rate is known only after the plug is initialized.
Thanks for reporting the issue, I'll investigate.

**Comment by brummer10** [comment]
I've pushed a fix for it now to the repository. 
Let me know if that fix it for you as well.

**Comment by felixniemeyer** [comment]
Can confirm: StompTuner working now as CLAP plugin for 48kHz which it didn't before. 
Awesome! Issue resolved :)

**Comment by RustoMCSpit** [comment]
running linux mint x server lts cinnamon.

 StompTuner-v0.4-linux-x86_64.tar.xz does not work
have not tested other linux variants

**Comment by RustoMCSpit** [comment]
StompTuner-v0.4-linux-arm64.tar.xz does not get recognised on my system

**Comment by brummer10** [comment]
Have you tried to build it yourself? As the latest fix wasn't released as binary

**Comment by RustoMCSpit** [comment]
> Have you tried to build it yourself? As the latest fix wasn't released as binary

i wouldnt even know how to apologies, i have to learn how to use podman to create environments before doing shit like that. can you build (again sorry i genuinely dont know how)

**Comment by brummer10** [comment]
> i have to learn how to use podman

So you use Arch Linux?

**Comment by brummer10** [comment]
Build it yourself is really not hard. Just follow the steps provided on the project page:
```
git clone --recursive https://github.com:brummer10/StompTuner
cd StompTuner
make
make install
```
that's all, no setup of podman or whatever is required.

**Comment by RustoMCSpit** [comment]
alright one sec

**Comment by RustoMCSpit** [comment]
> > i have to learn how to use podman
> 
> So you use Arch Linux?

linux mint

**Comment by RustoMCSpit** [comment]
off-topic
any update on this https://github.com/brummer10/XUiDesigner/issues/23

**Comment by RustoMCSpit** [comment]
~/Desktop/Untitled Folder$ git clone --recursive https://github.com:brummer10/StompTuner
Cloning into 'StompTuner'...
fatal: unable to access 'https://github.com:brummer10/StompTuner/': URL using bad/illegal format or missing URL

**Comment by RustoMCSpit** [comment]
??

**Comment by brummer10** [comment]
ups. my bad
`git clone --recursive https://github.com/brummer10/StompTuner.git`

**Comment by RustoMCSpit** [comment]
```
`:~/Desktop/Untitled` Folder/StompTuner$ make
cd dpf/dgl/src/pugl-upstream/ && git apply ../../../../pugl.patch
touch pugl_patch.flag
make -C dpf/dgl ../build/libdgl-cairo.a
make[1]: Entering directory '/home/tony/Desktop/Untitled Folder/StompTuner/dpf/dgl'
Compiling src/Application.cpp
Compiling src/ApplicationPrivateData.cpp
Compiling src/Color.cpp
Compiling src/EventHandlers.cpp
Compiling src/Geometry.cpp
Compiling src/ImageBase.cpp
Compiling src/ImageBaseWidgets.cpp
Compiling src/Layout.cpp
Compiling src/Resources.cpp
Compiling src/SubWidget.cpp
Compiling src/SubWidgetPrivateData.cpp
Compiling src/TopLevelWidget.cpp
Compiling src/TopLevelWidgetPrivateData.cpp
Compiling src/Widget.cpp
Compiling src/WidgetPrivateData.cpp
Compiling src/Window.cpp
Compiling src/WindowPrivateData.cpp
Compiling src/Cairo.cpp (Cairo variant)
In file included from src/Cairo.cpp:23:
src/../Cairo.hpp:23:10: fatal error: cairo.h: No such file or directory
   23 | #include <cairo.h>
      |          ^~~~~~~~~
```

**Comment by brummer10** [comment]
`sudo apt install libcairo2-dev`

**Comment by RustoMCSpit** [comment]
> `sudo apt install libcairo2-dev`

whats that

**Comment by RustoMCSpit** [comment]
pitch_tracker.h:28:10: fatal error: fftw3.h: No such file or directory
   28 | #include <fftw3.h>
      |          ^~~~~~~~~

**Comment by brummer10** [comment]
That's to install the missing dependency 
`sudo apt install libfftw3-dev`

**Comment by RustoMCSpit** [comment]
yeah i can see the gui now, that fixed it

**Comment by RustoMCSpit** [comment]
any reason why it went from 6mb to 270kb?

**Comment by RustoMCSpit** [comment]
> off-topic any update on this [brummer10/XUiDesigner#23](https://github.com/brummer10/XUiDesigner/issues/23)

?

**Comment by RustoMCSpit** [comment]
also off-topic, added your plugins here https://github.com/RustoMCSpit/awesome-linux-clap-list

**Comment by brummer10** [comment]
> any reason why it went from 6mb to 270kb?

Because you've now using your system libraries, (as it should be on linux) instead copied all used libraries over staticaly into the plugin.

> off-topic any update on this [brummer10/XUiDesigner#23](https://github.com/brummer10/XUiDesigner/issues/23)

Nope, as I said in the other thread, I already running out of time



> also off-topic, added your plugins here https://github.com/RustoMCSpit/awesome-linux-clap-list

Oh, that's nice, very welcome.

**Comment by felixniemeyer** [comment]
I received notifications about the recent conversation with @RustoMCSpit, because I authored this issue. 

I'm angry at @RustoMCSpit behavior. 
First of all, their issue is not related to this issue and this issue is already closed. 
Secondly, issues are not the place for requesting basic build support in general.
Finally, the way they are requesting help (e.g. impatiently following up with "??") is rude and disrespectful in my opinion.
